update github workflows and poetry lock file

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,107 +1,107 @@
-name: build
-
-# Build and test NautilusTrader
-
-on:
-  push:
-    branches: [master, develop]
-  pull_request:
-    branches: [develop]
-
-jobs:
-  build:
-    strategy:
-      fail-fast: false
-      matrix:
-        arch: [x64]
-        os: [ubuntu-latest, macos-latest]
-        python-version: ["3.11"]
-    name: build - Python ${{ matrix.python-version }} (${{ matrix.arch }} ${{ matrix.os }})
-    runs-on: ${{ matrix.os }}
-    env:
-      BUILD_MODE: debug
-      RUST_BACKTRACE: 1
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-
-      - name: Set up Rust tool-chain (Linux, Windows) stable
-        if: (runner.os == 'Linux') || (runner.os == 'Windows')
-        uses: actions-rust-lang/setup-rust-toolchain@v1.5
-        with:
-          toolchain: stable
-          components: rustfmt, clippy
-
-      # Work around as actions-rust-lang does not seem to work on macOS yet
-      - name: Set up Rust tool-chain (macOS) stable
-        if: runner.os == 'macOS'
-        uses: actions-rs/toolchain@v1
-        with:
-          toolchain: stable
-          override: true
-          components: rustfmt, clippy
-
-      - name: Set up Python environment
-        uses: actions/setup-python@v4
-        with:
-          python-version: ${{ matrix.python-version }}
-
-      - name: Install build dependencies
-        run: python -m pip install --upgrade pip setuptools wheel pre-commit poetry==1.6.1 msgspec
-
-      - name: Setup cached pre-commit
-        id: cached-pre-commit
-        uses: actions/cache@v3
-        with:
-          path: ~/.cache/pre-commit
-          key: ${{ runner.os }}-${{ matrix.python-version }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
-
-      - name: Setup poetry output (Linux, macOS)
-        if: (runner.os == 'Linux') || (runner.os == 'macOS')
-        run: echo "dir=$(poetry config cache-dir)" >> $GITHUB_ENV
-
-      - name: Setup poetry output (Windows)
-        if: runner.os == 'Windows'
-        run: echo "dir=$(poetry config cache-dir)" | Out-File -FilePath $env:GITHUB_ENV -Append >> $GITHUB_ENV
-
-      - name: Poetry cache
-        id: cached-poetry
-        uses: actions/cache@v3
-        with:
-          path: ${{ env.dir }}
-          key: ${{ runner.os }}-${{ matrix.python-version }}-poetry-${{ hashFiles('**/poetry.lock') }}
-
-      - name: Run pre-commit
-        run: pre-commit run --all-files
-
-      - name: Install Redis (macOS)
-        if: runner.os == 'macOS'
-        run: |
-          brew install redis
-          redis-server --daemonize yes
-
-      - name: Install Redis (Linux)
-        if: runner.os == 'Linux'
-        run: |
-          sudo apt-get install redis-server
-          redis-server --daemonize yes
-
-      - name: Run nautilus_core cargo tests (Linux, macOS)
-        if: (runner.os == 'Linux') || (runner.os == 'macOS')
-        run: make cargo-test
-
-      - name: Run tests (Linux, macOS)
-        if: (runner.os == 'Linux') || (runner.os == 'macOS')
-        run: |
-          make pytest
-          make test-examples
-
-      # Run tests without parallel build (avoids linker errors)
-      - name: Run tests (Windows)
-        if: runner.os == 'Windows'
-        run: |
-          poetry install --with test --all-extras
-          poetry run pytest --ignore=tests/performance_tests --new-first --failed-first
-        env:
-          PARALLEL_BUILD: false
+#name: build
+#
+## Build and test NautilusTrader
+#
+#on:
+#  push:
+#    branches: [master, develop]
+#  pull_request:
+#    branches: [develop]
+#
+#jobs:
+#  build:
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        arch: [x64]
+#        os: [ubuntu-latest, macos-latest]
+#        python-version: ["3.11"]
+#    name: build - Python ${{ matrix.python-version }} (${{ matrix.arch }} ${{ matrix.os }})
+#    runs-on: ${{ matrix.os }}
+#    env:
+#      BUILD_MODE: debug
+#      RUST_BACKTRACE: 1
+#
+#    steps:
+#      - name: Checkout repository
+#        uses: actions/checkout@v3
+#
+#      - name: Set up Rust tool-chain (Linux, Windows) stable
+#        if: (runner.os == 'Linux') || (runner.os == 'Windows')
+#        uses: actions-rust-lang/setup-rust-toolchain@v1.5
+#        with:
+#          toolchain: stable
+#          components: rustfmt, clippy
+#
+#      # Work around as actions-rust-lang does not seem to work on macOS yet
+#      - name: Set up Rust tool-chain (macOS) stable
+#        if: runner.os == 'macOS'
+#        uses: actions-rs/toolchain@v1
+#        with:
+#          toolchain: stable
+#          override: true
+#          components: rustfmt, clippy
+#
+#      - name: Set up Python environment
+#        uses: actions/setup-python@v4
+#        with:
+#          python-version: ${{ matrix.python-version }}
+#
+#      - name: Install build dependencies
+#        run: python -m pip install --upgrade pip setuptools wheel pre-commit poetry==1.6.1 msgspec
+#
+#      - name: Setup cached pre-commit
+#        id: cached-pre-commit
+#        uses: actions/cache@v3
+#        with:
+#          path: ~/.cache/pre-commit
+#          key: ${{ runner.os }}-${{ matrix.python-version }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
+#
+#      - name: Setup poetry output (Linux, macOS)
+#        if: (runner.os == 'Linux') || (runner.os == 'macOS')
+#        run: echo "dir=$(poetry config cache-dir)" >> $GITHUB_ENV
+#
+#      - name: Setup poetry output (Windows)
+#        if: runner.os == 'Windows'
+#        run: echo "dir=$(poetry config cache-dir)" | Out-File -FilePath $env:GITHUB_ENV -Append >> $GITHUB_ENV
+#
+#      - name: Poetry cache
+#        id: cached-poetry
+#        uses: actions/cache@v3
+#        with:
+#          path: ${{ env.dir }}
+#          key: ${{ runner.os }}-${{ matrix.python-version }}-poetry-${{ hashFiles('**/poetry.lock') }}
+#
+#      - name: Run pre-commit
+#        run: pre-commit run --all-files
+#
+#      - name: Install Redis (macOS)
+#        if: runner.os == 'macOS'
+#        run: |
+#          brew install redis
+#          redis-server --daemonize yes
+#
+#      - name: Install Redis (Linux)
+#        if: runner.os == 'Linux'
+#        run: |
+#          sudo apt-get install redis-server
+#          redis-server --daemonize yes
+#
+#      - name: Run nautilus_core cargo tests (Linux, macOS)
+#        if: (runner.os == 'Linux') || (runner.os == 'macOS')
+#        run: make cargo-test
+#
+#      - name: Run tests (Linux, macOS)
+#        if: (runner.os == 'Linux') || (runner.os == 'macOS')
+#        run: |
+#          make pytest
+#          make test-examples
+#
+#      # Run tests without parallel build (avoids linker errors)
+#      - name: Run tests (Windows)
+#        if: runner.os == 'Windows'
+#        run: |
+#          poetry install --with test --all-extras
+#          poetry run pytest --ignore=tests/performance_tests --new-first --failed-first
+#        env:
+#          PARALLEL_BUILD: false
