Test UV

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,7 +22,7 @@ jobs:
 
       - name: Run pre-commit
         continue-on-error: true
-        run: make pre-commit || echo "PRECOMMIT_FAILED=true" > $GITHUB_ENV
+        run: pre-commit run --all-files || echo "PRECOMMIT_FAILED=true" > $GITHUB_ENV
 
       # https://docs.github.com/en/rest/issues/comments#create-an-issue-comment
       - name: Add PR comment on failure
