Conditionally install cargo-nextest

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -152,7 +152,13 @@ jobs:
 
       - name: Run nautilus_core cargo tests (Linux)
         run: |
-          cargo install cargo-nextest --force
+          if ! command -v cargo-nextest &> /dev/null
+          then
+              echo "cargo-nextest not found, installing..."
+              cargo install cargo-nextest
+          else
+              echo "cargo-nextest is already installed"
+          fi
           make cargo-test
 
       - name: Run tests (Linux)
@@ -360,7 +366,13 @@ jobs:
 
       - name: Run nautilus_core cargo tests (macOS)
         run: |
-          cargo install cargo-nextest --force
+          if ! command -v cargo-nextest &> /dev/null
+          then
+              echo "cargo-nextest not found, installing..."
+              cargo install cargo-nextest
+          else
+              echo "cargo-nextest is already installed"
+          fi
           make cargo-test
 
       - name: Run tests (macOS)
