Update workflow

diff --git a/.github/workflows/test-tag-publish.yml b/.github/workflows/test-tag-publish.yml
--- a/.github/workflows/test-tag-publish.yml
+++ b/.github/workflows/test-tag-publish.yml
@@ -7,67 +7,69 @@ on:
     branches: [ master ]
 
 jobs:
-  test:
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ ubuntu-latest, macos-latest, windows-latest ]
-        python-version: [ 3.7, 3.8, 3.9 ]
-    name: test - Python ${{ matrix.python-version }} (${{ matrix.os }})
-    runs-on: ${{ matrix.os }}
-
-    steps:
-      - uses: actions/checkout@v2
-
-      # Python setup
-      - name: Set up Python environment
-        uses: actions/setup-python@v2
-        with:
-          python-version: ${{ matrix.python-version }}
-
-      # Install build dependencies
-      - name: Install build dependencies
-        run: python -m pip install --upgrade pip setuptools wheel poetry nox
-
-      # Setup Poetry caching
-      - name: Get Poetry cache dir
-        id: poetry-cache
-        run: echo "::set-output name=dir::$(poetry config cache-dir)"
-
-      - name: Poetry/Nox cache
-        uses: actions/cache@v2
-        with:
-          path: ${{ steps.poetry-cache.outputs.dir }}
-          key: ${{ runner.os }}-${{ matrix.python-version }}-poetry-test-${{ hashFiles('**/poetry.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-${{ matrix.python-version }}-poetry-test-
-            ${{ runner.os }}-${{ matrix.python-version }}-poetry-
-
-      # Install and run database dependencies
-      - name: Install Memurai (Windows)
-        if: runner.os == 'Windows'
-        run: |
-          choco install memurai-developer.install
-
-      - name: Install Redis (macOS)
-        if: runner.os == 'macOS'
-        run: |
-          brew install redis
-          redis-server --daemonize yes
-
-      - name: Install Redis (Linux)
-        if: runner.os == 'Linux'
-        run: |
-          sudo apt-get install redis-server
-          redis-server --daemonize yes
-
-      # Run tests
-      - name: Run tests
-        run: nox -s tests_with_integration --reuse-existing-virtualenvs
+# TODO: Uncomment for next release
+#  test:
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        os: [ windows-latest ]
+#        python-version: [ 3.7, 3.8, 3.9 ]
+#    name: test - Python ${{ matrix.python-version }} (${{ matrix.os }})
+#    runs-on: ${{ matrix.os }}
+#
+#    steps:
+#      - uses: actions/checkout@v2
+#
+#      # Python setup
+#      - name: Set up Python environment
+#        uses: actions/setup-python@v2
+#        with:
+#          python-version: ${{ matrix.python-version }}
+#
+#      # Install build dependencies
+#      - name: Install build dependencies
+#        run: python -m pip install --upgrade pip setuptools wheel poetry nox
+#
+#      # Setup Poetry caching
+#      - name: Get Poetry cache dir
+#        id: poetry-cache
+#        run: echo "::set-output name=dir::$(poetry config cache-dir)"
+#
+#      - name: Poetry/Nox cache
+#        uses: actions/cache@v2
+#        with:
+#          path: ${{ steps.poetry-cache.outputs.dir }}
+#          key: ${{ runner.os }}-${{ matrix.python-version }}-poetry-test-${{ hashFiles('**/poetry.lock') }}
+#          restore-keys: |
+#            ${{ runner.os }}-${{ matrix.python-version }}-poetry-test-
+#            ${{ runner.os }}-${{ matrix.python-version }}-poetry-
+#
+#      # Install and run database dependencies
+#      - name: Install Memurai (Windows)
+#        if: runner.os == 'Windows'
+#        run: |
+#          choco install memurai-developer.install
+#
+#      - name: Install Redis (macOS)
+#        if: runner.os == 'macOS'
+#        run: |
+#          brew install redis
+#          redis-server --daemonize yes
+#
+#      - name: Install Redis (Linux)
+#        if: runner.os == 'Linux'
+#        run: |
+#          sudo apt-get install redis-server
+#          redis-server --daemonize yes
+#
+#      # Run tests
+#      - name: Run tests
+#        run: nox -s tests_with_integration --reuse-existing-virtualenvs
 
 
   tag_release:
-    needs: [ test ]
+    # TODO: Uncomment for next release
+    # needs: [ test ]
     strategy:
       fail-fast: false
       matrix:
@@ -258,30 +260,28 @@ jobs:
           poetry install
           poetry build --format wheel
 
+      # Upload release asset (UNIX)
+      - name: Set output (UNIX)
+        id: vars-unix
+        if: (runner.os == 'Linux') || (runner.os == 'macOS')
+        run: |
+          echo "::set-output name=asset_path::$(find ./dist -mindepth 1 -print -quit)"
+          cd dist
+          echo "::set-output name=asset_name::$(printf '%s\0' * | awk 'BEGIN{RS="\0"} {print;  exit}')"
 
-# TODO: Uncomment for next release
-#      # Upload release asset (UNIX)
-#      - name: Set output (UNIX)
-#        id: vars-unix
-#        if: (runner.os == 'Linux') || (runner.os == 'macOS')
-#        run: |
-#          echo "::set-output name=asset_path::$(find ./dist -mindepth 1 -print -quit)"
-#          cd dist
-#          echo "::set-output name=asset_name::$(printf '%s\0' * | awk 'BEGIN{RS="\0"} {print;  exit}')"
-#
-#      - name: Upload release asset (UNIX)
-#        id: upload-release-asset-unix
-#        if: (runner.os == 'Linux') || (runner.os == 'macOS')
-#        uses: actions/upload-release-asset@v1
-#        env:
-#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-#          ASSET_PATH: ${{ steps.vars-unix.outputs.asset_path }}
-#          ASSET_NAME: ${{ steps.vars-unix.outputs.asset_name }}
-#        with:
-#          upload_url: ${{ needs.tag_release.outputs.upload_url }}
-#          asset_path: ${{ env.ASSET_PATH }}
-#          asset_name: ${{ env.ASSET_NAME }}
-#          asset_content_type: application/wheel
+      - name: Upload release asset (UNIX)
+        id: upload-release-asset-unix
+        if: (runner.os == 'Linux') || (runner.os == 'macOS')
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          ASSET_PATH: ${{ steps.vars-unix.outputs.asset_path }}
+          ASSET_NAME: ${{ steps.vars-unix.outputs.asset_name }}
+        with:
+          upload_url: ${{ needs.tag_release.outputs.upload_url }}
+          asset_path: ${{ env.ASSET_PATH }}
+          asset_name: ${{ env.ASSET_NAME }}
+          asset_content_type: application/wheel
 
       # Upload release asset (Windows)
       - name: Set output (Windows)
